[package]
name = "spl-token-names"
version = "0.1.0"
authors = ["Guanqun Lu <guanqun.lu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
